### ISSUE TITLE
bug in model_parameters of snas

### ISSUE THREAD

**Issue by MarkAlive** [JunrQ/NAS#6]
Thanks for yours code! I think 'and' in line 224 should be changed to 'or'.

https://github.com/JunrQ/NAS/blob/d430c326e2d7f8cce10051c36c669fc54f10874c/snas/snas/snas.py#L224

**Comment by JunrQ** [comment]
> Thanks for yours code! I think 'and' in line 224 should be changed to 'or'.
> 
> [NAS/snas/snas/snas.py](https://github.com/JunrQ/NAS/blob/d430c326e2d7f8cce10051c36c669fc54f10874c/snas/snas/snas.py#L224)
> 
> Line 224 in [d430c32](/JunrQ/NAS/commit/d430c326e2d7f8cce10051c36c669fc54f10874c)
>  if not ('alphas_nomal' in k[0] and 'alphas_reduce' in k[0]):

I think you are right, thank u.

**Comment by MarkAlive** [comment]
hi @JunrQ , 'alphas_nomal' should also need to be changed to 'alphas_normal' in the same line.

**Comment by JunrQ** [comment]
> hi @JunrQ , 'alphas_nomal' should also need to be changed to 'alphas_normal' in the same line.

You are right, thanks.
Sorry for my mistake.
