### ISSUE TITLE
what meaning MAC means in MixedOp?

### ISSUE THREAD

**Issue by MarkAlive** [JunrQ/NAS#9]
In my understanding, MAC means "Multipy Add Cost", but the following code seams to calculate the memory cost of DilConv.

`        MAC1 = (self.width * self.height) * (op.op[1].in_channels + op.op[1].in_channels)
        MAC1 += (op.op[1].kernel_size[0] ** 2 *op.op[1].in_channels * op.op[1].out_channels) / op.op[1].groups
        MAC2 = (self.width * self.height) * (op.op[2].in_channels + op.op[2].in_channels)
        MAC2 += (op.op[2].kernel_size[0] ** 2 *op.op[2].in_channels * op.op[2].out_channels) / op.op[2].groups
        
        MAC = MAC1 + MAC2
`

https://github.com/JunrQ/NAS/blob/5c23276c0e1bb433ff0f325aa8642e36ac8deee7/snas/snas/snas.py#L55

**Comment by JunrQ** [comment]
Thanks.

In the paper, MAC : memory access cost

I update the calculation code for FLOPS and MAC.
Please check if there is anything wrong.

**Comment by MarkAlive** [comment]
Hi @JunrQ , thanks for the quick respond! 

The calculation is more clear than before!

I have a new question: Is 'C**2' correct in https://github.com/JunrQ/NAS/blob/e25a4640323c09d8ab5d09e9cca8f5e6e74c6202/snas/snas/snas.py#L86 ? Why? THX!

**Comment by JunrQ** [comment]
FLOPS = width * height * kernel_h * kernel_w * in_channels * out_channels
kernel_h = kernel_w = 3
in_channels = out_channels = C

**Comment by MarkAlive** [comment]
In pooling layer, if I understand correctly, every out_channel is calculated from one in_channel. This is why in_channels is equal to out_channels.

**Comment by JunrQ** [comment]
It seems that you find an error in the paper of SNAS
In the paper, the FLOPs of pooling is : **FLOPs=HWfkIO**

But as you said, and the [formulation](https://pytorch.org/docs/stable/nn.html?highlight=pool#torch.nn.AvgPool2d) shows
the FLOPs of Pooling should be **FLOPs = HWfkI**
